// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: proto/go_calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение для запроса задачи
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_go_calc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_calc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_go_calc_proto_rawDescGZIP(), []int{0}
}

// Сообщение для ответа с задачей
type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Идентификатор задачи
	Arg1          float32                `protobuf:"fixed32,2,opt,name=arg1,proto3" json:"arg1,omitempty"`                                       // Имя первого аргумента
	Arg2          float32                `protobuf:"fixed32,3,opt,name=arg2,proto3" json:"arg2,omitempty"`                                       // Имя второго аргумента
	Operation     string                 `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`                               // Операция
	OperationTime int64                  `protobuf:"varint,5,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"` // Время выполнения операции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_go_calc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_calc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_go_calc_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetArg1() float32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *Task) GetArg2() float32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

func (x *Task) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Task) GetOperationTime() int64 {
	if x != nil {
		return x.OperationTime
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"` // Задача
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_proto_go_calc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_calc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_go_calc_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

// Сообщение для приема результата обработки данных
type PostResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`          // Идентификатор задачи
	Result        float32                `protobuf:"fixed32,2,opt,name=result,proto3" json:"result,omitempty"` // Результат обработки данных
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // Ошибка
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResultRequest) Reset() {
	*x = PostResultRequest{}
	mi := &file_proto_go_calc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResultRequest) ProtoMessage() {}

func (x *PostResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_calc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResultRequest.ProtoReflect.Descriptor instead.
func (*PostResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_go_calc_proto_rawDescGZIP(), []int{3}
}

func (x *PostResultRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostResultRequest) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PostResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Сообщение для ответа на прием результата
type PostResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResultResponse) Reset() {
	*x = PostResultResponse{}
	mi := &file_proto_go_calc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResultResponse) ProtoMessage() {}

func (x *PostResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_go_calc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResultResponse.ProtoReflect.Descriptor instead.
func (*PostResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_go_calc_proto_rawDescGZIP(), []int{4}
}

func (x *PostResultResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_go_calc_proto protoreflect.FileDescriptor

const file_proto_go_calc_proto_rawDesc = "" +
	"\n" +
	"\x13proto/go_calc.proto\x12\ago_calc\"\x10\n" +
	"\x0eGetTaskRequest\"\x83\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04arg1\x18\x02 \x01(\x02R\x04arg1\x12\x12\n" +
	"\x04arg2\x18\x03 \x01(\x02R\x04arg2\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12%\n" +
	"\x0eoperation_time\x18\x05 \x01(\x03R\roperationTime\"4\n" +
	"\x0fGetTaskResponse\x12!\n" +
	"\x04task\x18\x01 \x01(\v2\r.go_calc.TaskR\x04task\"Q\n" +
	"\x11PostResultRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x02R\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\",\n" +
	"\x12PostResultResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x92\x01\n" +
	"\vTaskService\x12<\n" +
	"\aGetTask\x12\x17.go_calc.GetTaskRequest\x1a\x18.go_calc.GetTaskResponse\x12E\n" +
	"\n" +
	"PostResult\x12\x1a.go_calc.PostResultRequest\x1a\x1b.go_calc.PostResultResponseB%Z#github.com/f1rsov08/go_calc_2/protob\x06proto3"

var (
	file_proto_go_calc_proto_rawDescOnce sync.Once
	file_proto_go_calc_proto_rawDescData []byte
)

func file_proto_go_calc_proto_rawDescGZIP() []byte {
	file_proto_go_calc_proto_rawDescOnce.Do(func() {
		file_proto_go_calc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_go_calc_proto_rawDesc), len(file_proto_go_calc_proto_rawDesc)))
	})
	return file_proto_go_calc_proto_rawDescData
}

var file_proto_go_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_go_calc_proto_goTypes = []any{
	(*GetTaskRequest)(nil),     // 0: go_calc.GetTaskRequest
	(*Task)(nil),               // 1: go_calc.Task
	(*GetTaskResponse)(nil),    // 2: go_calc.GetTaskResponse
	(*PostResultRequest)(nil),  // 3: go_calc.PostResultRequest
	(*PostResultResponse)(nil), // 4: go_calc.PostResultResponse
}
var file_proto_go_calc_proto_depIdxs = []int32{
	1, // 0: go_calc.GetTaskResponse.task:type_name -> go_calc.Task
	0, // 1: go_calc.TaskService.GetTask:input_type -> go_calc.GetTaskRequest
	3, // 2: go_calc.TaskService.PostResult:input_type -> go_calc.PostResultRequest
	2, // 3: go_calc.TaskService.GetTask:output_type -> go_calc.GetTaskResponse
	4, // 4: go_calc.TaskService.PostResult:output_type -> go_calc.PostResultResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_go_calc_proto_init() }
func file_proto_go_calc_proto_init() {
	if File_proto_go_calc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_go_calc_proto_rawDesc), len(file_proto_go_calc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_go_calc_proto_goTypes,
		DependencyIndexes: file_proto_go_calc_proto_depIdxs,
		MessageInfos:      file_proto_go_calc_proto_msgTypes,
	}.Build()
	File_proto_go_calc_proto = out.File
	file_proto_go_calc_proto_goTypes = nil
	file_proto_go_calc_proto_depIdxs = nil
}
